### ISSUE TITLE
How to render firstName in the group conversation

### ISSUE THREAD

**Issue by shamxeed** [flyerhq/react-native-chat-ui#30]
Hi There! Thanks for this amazing library but I'm finding it a bit hard to show users names in group chat, how can I archive that, please??

**Comment by demchenkoalex** [comment]
Hey @shamxeed it's in the PR and coming soon with the 1.1 version (it will be a breaking change to stabilize the API)

**Comment by shamxeed** [comment]
Okay, glad to hear that and thanks for the amazing work!! Just for my curiosity, when are we going to expect the v1.1 release?

Thank You So Much Once Again!!!

**Comment by demchenkoalex** [comment]
Should be this week :)

**Comment by demchenkoalex** [comment]
Update is available on `main` branch, I still need to update documentation and add a couple of small tweaks, that's why no release, but it is working from git if urgently needed :)

**Comment by shamxeed** [comment]
Can't thank you enough @demchenkoalex !! Because it's surely urgently needed!! :))

**Comment by demchenkoalex** [comment]
Released on NPM too [v1.3.0](https://github.com/flyerhq/react-native-chat-ui/releases/tag/v1.3.0). Firebase package next.

**Comment by shamxeed** [comment]
@demchenkoalex that's a huge update and making this library more complete😍😍... Just that onChangeText method need to be accessed in order to show when user is typing...

Thanks for the hardwork!!

**Comment by demchenkoalex** [comment]
Hi @shamxeed it is there, just use `textInputProps` and a usual `onChangeText`. We tried to supply props for basic RN components using this objects, like `textInputProps` or `flatListProps` etc.

**Comment by shamxeed** [comment]
@demchenkoalex  Wow!! This is absolutely mind-blowing now everything I need is packed with this library❤️❤️❤️

Just a friendly advice, do you think in the Group Chat showing firstName/lastName is the best option ?? For me, I think using a username will be a good practice, as it can uniquely identify users and many more...

Thank you once again for always being here❤️❤️

**Comment by demchenkoalex** [comment]
Hey @shamxeed we thought that if someone has usernames, firstName will be username and lastName will not exist, so you have usernames. WDYT?

**Comment by shamxeed** [comment]
@demchenkoalex sorry for the late response, I was actually on break that's why.  Yeah, that might be possible but it's also possible that usernames are actual set by users while registering/account creation, with some rules e.g: it must be unique and can't contain generic terms or extensions (.com, .net), and capitalization can't be used to differentiate usernames etc... But firstName or fullName can be anything even emojis in some cases lol. And are (firstName/fullName) used mostly for displayName.

Refernces: Snapchat & Twitter.

Thanks!!!

**Comment by shamxeed** [comment]
There's another thing I want to draw your attention about, that's the `createdAt` field on chat which expect timestamp and must be `Number` that's really good actually, but the thing is that sometimes some databases return `dateField` in `String` which is opposed to what this library expects.

If you consider this as something to be addressed, then I think the code needs to be redefined in a way that  `Number`/`String` does not matter.

e.g

```js

const compare = (a, b) => new Date(+a.createdAt) - new Date(+b.createdAt) 

const sortedInAsc = data.sort(compare)

```

Thank you so much!!! ❤️❤️

**Comment by demchenkoalex** [comment]
Hey @shamxeed no problem, hope you're enjoyed your time off :)

Both of your cases are not related to this library, because this is not the app, this is a component that helps you to render a chat, nothing more. It does not handle registration, it does not handle millions of date formats that exist. 

In order for such library to function you **need to** create some hard coded fields like `createdAt` because there is some logic to be handled, and you can't accept a generic because people will start throwing in numbers, strings, objects, arrays etc. How does one handle all that?

Instead, some fields are forced to be something specific, and library user **must** transform his backed responses or write registration logic (see username logic) in order to supply the correct data.

This library is just a helper/time saver, but you **have to** do something in order to use it, everything has its price :)

**Comment by shamxeed** [comment]
Thanks, @demchenkoalex I completely understand... Hats off!!!
