### ISSUE TITLE
No displaying activity indicator when use Firestore/Pagination

### ISSUE THREAD

**Issue by nericode** [flyerhq/react-native-chat-ui#35]
In this section, the activityIndicator will only be activated without onEndReached it is asynchronous, but firestore isnt asynchronous so it will never generate an activityIndicator

```js
setNextPageLoading(true)
await onEndReached?.()
setNextPageLoading(false)
```

https://github.com/flyerhq/react-native-chat-ui/blob/242a30a6aba85ea379fb690d60079ec034858acc/src/components/Chat/Chat.tsx#L223

**Expected**: 
The activityindicator should be shown loading, until new information is received

Is there some other way to handle the activityIndicator?

**Comment by demchenkoalex** [comment]
Hey @nericode there is no other way unfortunately :( this is how it was designed. Do you have maybe other ideas? Because there are tons of pagination strategies, making an asynchronous function was the solution to fit everything, however I agree with you, it will not work for non asynchronous tasks. Is there a way in Firebase to make it asynchronous? I am wondering how they do it, because data still need to be loaded and how is it synchronous?

**Comment by nericode** [comment]
Yes i have this code: 

```js 
firestore()
    .collection(`conversations/${conversationId}/messages`)
    .orderBy('createdAt', 'desc')
    .limit(LIMIT_PAGE)
    .onSnapshot(snapshot => {
      populateMessages(snapshot);
    });
```
So no have async method, I managed to encapsulate this in a Promise and this made the activityIndicator work.

``` js
return new Promise((resolve, reject) => {
   firestore()
    .collection(`conversations/${conversationId}/messages`)
    .orderBy('createdAt', 'desc')
    .startAfter(lastDocument)
    .limit(LIMIT_PAGE)
    .onSnapshot(snapshot => {
      resolve();
    });
});
```

**Comment by demchenkoalex** [comment]
Wow, thanks for sharing!
